version: '3.7'

services:
  dbimport:
    build: .
    restart: unless-stopped
    command: /usr/local/bin/httpcheck-dbimport
    env_file: .env
    volumes:
      - .:/usr/src/app
  httpcheck:
    build: .
    restart: unless-stopped
    command: /usr/local/bin/httpcheck --websites ./websites.json
    env_file: .env
    environment:
      - "DEBUG=1"
    volumes:
      - .:/usr/src/app
