version: '3.7'

services:
  httpcheck:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: httpcheck_dev
    restart: unless-stopped
    working_dir: /usr/src/app
    command: /usr/local/bin/httpcheck --websites ./websites.json
    env_file: .env
    environment:
      - "LOG_LEVEL=INFO"
    volumes:
      - .:/usr/src/app
